### ISSUE TITLE
Feature request: support in bioconda

### ISSUE THREAD

**Issue by rspreafico-vir** [broadinstitute/rnaseqc#19]
Most bioinformatic tools nowadays are available through bioconda. Would you consider updating the bioconda recipe for RNASeQC from the legacy 1.x series to the current 2.x series?

Thank you

**Comment by agraubert** [comment]
Thanks for the suggestion! I need to look into how to integrate Bioconda deployments with our existing CI infrastructure, but I should be able to get around to this soon.

In the meantime, you can download the latest static binaries (which should run with no setup) [here](https://github.com/broadinstitute/rnaseqc/releases). Or use the auto-updated docker `gcr.io/broad-cga-aarong-gtex/rnaseqc`

**Comment by rspreafico-vir** [comment]
Great, thank you! In the meantime, would it be possible to add the plotting Python scripts to the Docker container? They seem absent from `/opt/rnaseqc`.

**Comment by agraubert** [comment]
The scripts are currently saved in `/scripts`. I apologize for the lack of documentation regarding the docker image

**Comment by rspreafico-vir** [comment]
Awesome, thank you for this info!

**Comment by agraubert** [comment]
# Bioconda Roadmap

Tracking progress for adding bioconda recipe and connecting it to existing CI

- [ ] Update existing recipe (`rna-seqc`)
  * Should download and unzip latest static binary for target platform to `$PREFIX/bin`
  * Should download and unzip latest source tarball to `$PREFIX/src`
  * Should install python dependencies
  * Should create wrapper files in `$PREFIX/bin` for `rnaseqc-plot` and `rnaseqc-remap`
- [ ] Configure auto-update templates
  * `build.sh` which should be more or less static
  * `meta.yaml` which just needs version and sha hash updating
  * PR template which probably just needs version updating
- [ ] Integrate with existing CI
   * add `hub` as a brew dependency
   * run during `after_deploy`
   * clone forked bioconda-recipes repo
   * run auto-update script (above) to modify the repo then use hub to post a PR
---
This is probably going to take a while. On top of the work above, I also need to read up on how conda recipes work so that I can actually do everything I want to. It may take a few weeks to get this done
