### ISSUE TITLE
Feature request: additional metric columns

### ISSUE THREAD

**Issue by bknisbac** [broadinstitute/rnaseqc#21]
I recommend adding columns indicating: 
1. If reads are PE/SE
2. chimeric_read_rate and not just read count

**Comment by agraubert** [comment]
Can you please confirm some things for me?

1) All reads are, by default, considered paired. Running RNA-SeQC in `--unpaired` mode will treat all reads as single end. RNA-SeQC cannot handle bams with a mix of paired and single end. Are you looking for clarification in the Docs regarding this?

2) There are several metrics that are only reported as raw counts, because we decided that the rate was not commonly used. I can add that rate when I get a chance, but, in the meantime, you can compute the rate by dividing "Chimeric Reads" by "Total Reads" or "Mapped Reads" (depending on what you're looking for).

**Comment by bknisbac** [comment]
1. I now noticed the 'Unpaired reads' output in the metrics.tsv file. That sufficiently already covers my request. 

2.  Thanks -- I think it is useful.

**Comment by agraubert** [comment]
Great. I'll add Chimeric Rate with the next update

**Comment by agraubert** [comment]
Closed in 40f8467
